version: "3.9"

services:
  accountsdb:
    image: mysql:latest
    container_name: accountsdb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: accountsdb
    networks:
      - sambank
    volumes:
      - accounts_data:/var/lib/mysql

  loansdb:
    image: mysql:latest
    container_name: loansdb
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: loansdb
    networks:
      - sambank
    volumes:
      - loans_data:/var/lib/mysql

  cardsdb:
    image: mysql:latest
    container_name: cardsdb
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cardsdb
    networks:
      - sambank
    volumes:
      - cards_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - sambank
    volumes:
      - redis_data:/data

networks:
  sambank:
    driver: "bridge"

volumes:
  accounts_data:
  loans_data:
  cards_data:
  redis_data:
