spring:
  application:
    name: gatewayserver
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true


info:
  app:
    name: "Gateway Server"
    description: " gateway Microservice"
    version: "1.0.0"