server:
  port: 8072

eureka:
  instance:
    hostName: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostName}:8070/eureka/